export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const FETCH_POST_DETAILS = 'FETCH_POST_DETAILS';
export const UPDATE_POST_DETAILS = 'UPDATE_POST_DETAILS';
export const DELETE_POST_DETAILS = 'DELETE_POST_DETAILS';
export const CREATE_POST_DETAILS = 'CREATE_POST_DETAILS';
